[package]
name = "lvcs"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
lvcs-core = { path = "../lvcs-core" }
lvcs-net = { path = "../lvcs-net" }
time.workspace = true
rustls.workspace = true
tokio.workspace = true
